# Generated by Django 2.2.7 on 2019-12-16 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='neddy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('hospital', models.CharField(max_length=50)),
                ('blood_Type', models.CharField(max_length=3)),
                ('age', models.IntegerField()),
                ('donation_type', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('desciption', models.TextField(default='', max_length=1000)),
            ],
        ),
    ]
