# Generated by Django 2.2.7 on 2019-12-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needy', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='neddy',
            new_name='needy',
        ),
    ]
