# Generated by Django 2.2.7 on 2019-12-17 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('needy', '0002_auto_20191216_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
