# Generated by Django 3.0 on 2019-12-15 23:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AboutUs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='content',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='img',
            field=models.ImageField(default=2, upload_to='AboutUsimgs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
