# Generated by Django 2.2.7 on 2019-12-17 18:59

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='donator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=250)),
                ('bloodType', models.CharField(max_length=3)),
                ('dateOfLastDanation', models.DateField(default=datetime.datetime)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete='None', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
