# Generated by Django 2.2.7 on 2019-12-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donator',
            name='dateOfLastDanation',
        ),
    ]
